ARG cf_api_token
ARG cf_user_id

FROM node:20

WORKDIR /code

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

ENV cf_api_token=$cf_api_token
ENV cf_user_id=$cf_user_id

CMD [ "node", "dist/index.js" ]